# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "PyYAML" = super.buildPythonPackage rec {
    pname = "PyYAML";
    version = "6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/36/2b/61d51a2c4f25ef062ae3f74576b01638bebad5e045f747ff12643df63844/PyYAML-6.0.tar.gz";
      sha256 = "18imkjacvpxfgg1lbpraqywx3j7hr5dv99d242byqvrh2jf53yv8";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "allure-pytest" = super.buildPythonPackage rec {
    pname = "allure-pytest";
    version = "2.12.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d8/79/6f1a548e843142f01461bb22b3d687cca6586d7b36587e8cc22bbddadc2a/allure_pytest-2.12.0-py3-none-any.whl";
      sha256 = "0b2qnns1xlgqq9vi6y0l7phmgs4ir59hm2dysybk0i1lhfvv440s";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."allure-python-commons"
      self."pytest"
      self."six"
    ];
  };
  "allure-python-commons" = super.buildPythonPackage rec {
    pname = "allure-python-commons";
    version = "2.12.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bd/1a/5ae8dff91112e9eb752fc28f23d9973d206383ea0ce7ebd09be0398de43d/allure_python_commons-2.12.0-py3-none-any.whl";
      sha256 = "0d015vn8naxbs0wf45487xkapjmg4j7mgxif9wkwysv59sfwcs7r";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."pluggy"
      self."six"
    ];
  };
  "attrs" = super.buildPythonPackage rec {
    pname = "attrs";
    version = "22.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fb/6e/6f83bf616d2becdf333a1640f1d463fef3150e2e926b7010cb0f81c95e88/attrs-22.2.0-py3-none-any.whl";
      sha256 = "0dh84hdmdqvlyjqw0dqfbvfg6y4gh7w9h3qp96yqv1kqcxzmrs99";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "cardano-clusterlib" = super.buildPythonPackage rec {
    pname = "cardano-clusterlib";
    version = "0.4.0rc2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/85/65/1673baf6ad53c32b33a561e0afcad0f3a9a9eb1e2d8d09829cdfc8419683/cardano_clusterlib-0.4.0rc2-py3-none-any.whl";
      sha256 = "0j1jkd6nn43wf9j0yfal4dswfja7qjyhkj5znykg9a779452p8i2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."setuptools"
    ];
  };
  "cbor2" = super.buildPythonPackage rec {
    pname = "cbor2";
    version = "5.4.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d9/69/de486293f5211d2e8fe1a19854e69f2811a18448162c52b48c67f8fbcac3/cbor2-5.4.6.tar.gz";
      sha256 = "1mwlwpqsjgfmdzcd4sq2h3i5gz7fyrm9bp1s1ibkw0zyn06m14xq";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "certifi" = super.buildPythonPackage rec {
    pname = "certifi";
    version = "2022.12.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/71/4c/3db2b8021bd6f2f0ceb0e088d6b2d49147671f25832fb17970e9b583d742/certifi-2022.12.7-py3-none-any.whl";
      sha256 = "065wqxligjai8la891i71s921q7xmpyc3krixhc6fvcjbqpj7lsa";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "charset-normalizer" = super.buildPythonPackage rec {
    pname = "charset-normalizer";
    version = "3.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/96/d7/1675d9089a1f4677df5eb29c3f8b064aa1e70c1251a0a8a127803158942d/charset-normalizer-3.0.1.tar.gz";
      sha256 = "0vrjmv6w2hx0paknyq79gxhrrqn60q8r56v9g9fwmy1hz6d37spb";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "exceptiongroup" = super.buildPythonPackage rec {
    pname = "exceptiongroup";
    version = "1.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e8/14/9c6a7e5f12294ccd6975a45e02899ed25468cd7c2c86f3d9725f387f9f5f/exceptiongroup-1.1.0-py3-none-any.whl";
      sha256 = "07pc9dpm531932k6rlf40ak70dvvmf0pn45367h2svkmvaivsz1j";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "execnet" = super.buildPythonPackage rec {
    pname = "execnet";
    version = "1.9.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/81/c0/3072ecc23f4c5e0a1af35e3a222855cfd9c80a1a105ca67be3b6172637dd/execnet-1.9.0-py2.py3-none-any.whl";
      sha256 = "0hm1637il333zil593sxvwmc805ayj2xqzyyip2slis9fz6gg5d2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "filelock" = super.buildPythonPackage rec {
    pname = "filelock";
    version = "3.9.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/14/4c/b201d0292ca4e0950f0741212935eac9996f69cd66b92a3587e594999163/filelock-3.9.0-py3-none-any.whl";
      sha256 = "0vfidfgvqfqp1nzmcy0sq0ca8lw53xs6y16zsifavfcvz1d573gm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "hypothesis" = super.buildPythonPackage rec {
    pname = "hypothesis";
    version = "6.62.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7e/67/5fb5b438ea0ae495ef221c9d8637d8f81e0a8c8cc7ac9939940e50388760/hypothesis-6.62.1-py3-none-any.whl";
      sha256 = "038n9vwfc04q60c6fzjh98xrfyl0jliy9az11xbv9f5hajf4l2nh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."exceptiongroup"
      self."sortedcontainers"
    ];
  };
  "idna" = super.buildPythonPackage rec {
    pname = "idna";
    version = "3.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/34/3030de6f1370931b9dbb4dad48f6ab1015ab1d32447850b9fc94e60097be/idna-3.4-py3-none-any.whl";
      sha256 = "1hn54ps4kgv2fmyvfaks38sgrvjc1cn4834sh7gadsx3x9wpxdwh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "iniconfig" = super.buildPythonPackage rec {
    pname = "iniconfig";
    version = "2.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ef/a6/62565a6e1cf69e10f5727360368e451d4b7f58beeac6173dc9db836a5b46/iniconfig-2.0.0-py3-none-any.whl";
      sha256 = "0x43fyv1hpwpmvvqh73ldcyac9j2hb14mffis8i3nblxlxqmia5n";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "packaging" = super.buildPythonPackage rec {
    pname = "packaging";
    version = "23.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/35/a31aed2993e398f6b09a790a181a7927eb14610ee8bbf02dc14d31677f1c/packaging-23.0-py3-none-any.whl";
      sha256 = "1ch201bz087xfagzsy0hdyxz719bg9gq804vqacqrrn3jr2c2jki";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pluggy" = super.buildPythonPackage rec {
    pname = "pluggy";
    version = "1.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9e/01/f38e2ff29715251cf25532b9082a1589ab7e4f571ced434f98d0139336dc/pluggy-1.0.0-py2.py3-none-any.whl";
      sha256 = "1lvvnc39v43v5jawq2wz0765rg9lkx8f25l4sqv1l0vz8nzln4vl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "psycopg2-binary" = super.buildPythonPackage rec {
    pname = "psycopg2-binary";
    version = "2.9.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8c/45/77147700f5088efaf9235a3a62b611b594d477a5c5613b5316d0ebd18be0/psycopg2-binary-2.9.5.tar.gz";
      sha256 = "0774xkj7vswip6kxqad56k3cv7hfqh3912b5f6wsi5avi3835rik";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "py" = super.buildPythonPackage rec {
    pname = "py";
    version = "1.11.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f6/f0/10642828a8dfb741e5f3fbaac830550a518a775c7fff6f04a007259b0548/py-1.11.0-py2.py3-none-any.whl";
      sha256 = "0y5k0mjcr85i9xrd2wifc7gww596nq6dbz6d9bzpsr1jhwhm6z30";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pydantic" = super.buildPythonPackage rec {
    pname = "pydantic";
    version = "1.10.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/53/17/34e54e352f6a3d304044e52d5ddd5cd621a62ec8fb7af08cc73af65dd3e1/pydantic-1.10.4.tar.gz";
      sha256 = "0j56b523lqbhvc72x7nx0dhrpdxbnas1zgm309shjkpb4jgqb8xr";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."typing-extensions"
    ];
  };
  "pytest" = super.buildPythonPackage rec {
    pname = "pytest";
    version = "7.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fb/d0/bae533985f2338c5d02184b4a7083b819f6b3fc101da792e0d96e6e5299d/pytest-7.1.2-py3-none-any.whl";
      sha256 = "0g2388y4v095wyzl753i5sipp9ibhf65ddhc02z2cvibzk6f7l0k";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."iniconfig"
      self."packaging"
      self."pluggy"
      self."py"
      self."tomli"
    ];
  };
  "pytest-forked" = super.buildPythonPackage rec {
    pname = "pytest-forked";
    version = "1.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0c/36/c56ef2aea73912190cdbcc39aaa860db8c07c1a5ce8566994ec9425453db/pytest_forked-1.4.0-py3-none-any.whl";
      sha256 = "1n4a7idfmkycla6vwxhjc34z7ykw96qizd1p8pbbk1n8xwbngfxv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."py"
      self."pytest"
    ];
  };
  "pytest-html" = super.buildPythonPackage rec {
    pname = "pytest-html";
    version = "3.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/81/e1/35ae038e10ba11758e7d572f656ea7b99795f3d37d20aa40a5d7e8050091/pytest_html-3.2.0-py3-none-any.whl";
      sha256 = "1wzk4yw2wqi899w36z0j3rdv76s1g0qy7wb6d31b5n3899b0i346";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."py"
      self."pytest"
      self."pytest-metadata"
    ];
  };
  "pytest-metadata" = super.buildPythonPackage rec {
    pname = "pytest-metadata";
    version = "2.0.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e1/00/c8175f054e801b5d8135ef2d0d7e4ad508c0af94d81e521431c23cf56e8f/pytest_metadata-2.0.4-py3-none-any.whl";
      sha256 = "057ff8cvr092mym106a4g8v64c006p0f1scrq2cdgcxbkzw3kdxc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pytest"
    ];
  };
  "pytest-order" = super.buildPythonPackage rec {
    pname = "pytest-order";
    version = "1.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/03/e7/fc6934462f6b68a98561032243f3d9241bb5aa61fc79469288dc4a353353/pytest_order-1.0.1-py3-none-any.whl";
      sha256 = "1fqvzplfkmkp5m8m158gnybyf5vkxb8mim0hx2rilx13iqxfdrmv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pytest"
    ];
  };
  "pytest-select" = super.buildPythonPackage rec {
    pname = "pytest-select";
    version = "0.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/03/c6/f07fbbefda11038f14607d1f1ba80f9e8bdaae1a291dee04db8514b481fb/pytest_select-0.1.2-py3-none-any.whl";
      sha256 = "0yq200xvqvn4ny40hqplj2nai03gjl2k7xjhmbyfivwp8ch6hh6x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pytest"
    ];
  };
  "pytest-xdist" = super.buildPythonPackage rec {
    pname = "pytest-xdist";
    version = "2.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/21/08/b1945d4b4986eb1aa10cf84efc5293bba39da80a2f95db3573dd90678408/pytest_xdist-2.5.0-py3-none-any.whl";
      sha256 = "0rffs118z76kjm3bvrvq95s2483qbimn2ardizmnv44qxi7wgrbg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."execnet"
      self."pytest"
      self."pytest-forked"
    ];
  };
  "requests" = super.buildPythonPackage rec {
    pname = "requests";
    version = "2.28.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d2/f4/274d1dbe96b41cf4e0efb70cbced278ffd61b5c7bb70338b62af94ccb25b/requests-2.28.2-py3-none-any.whl";
      sha256 = "1alba73bi3rnpns28wf3b7ii2y0d3iw0n0rcc93sfg92154ryab4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."charset-normalizer"
      self."idna"
      self."urllib3"
    ];
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.16.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl";
      sha256 = "0m02dsi8lvrjf4bi20ab6lm7rr6krz7pg6lzk3xjs2l9hqfjzfwa";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sortedcontainers" = super.buildPythonPackage rec {
    pname = "sortedcontainers";
    version = "2.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/32/46/9cb0e58b2deb7f82b84065f37f3bffeb12413f947f9388e4cac22c4621ce/sortedcontainers-2.4.0-py2.py3-none-any.whl";
      sha256 = "1q3y4gdrb1d3595sxqlpk0j783hr8n9a6mz9hla0470gvspdqqx1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tomli" = super.buildPythonPackage rec {
    pname = "tomli";
    version = "2.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/97/75/10a9ebee3fd790d20926a90a2547f0bf78f371b2f13aa822c759680ca7b9/tomli-2.0.1-py3-none-any.whl";
      sha256 = "1k0fqfdylinb57s2aqwprahwbrsk3babg4gghz4g06hnlvky77ck";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "typing-extensions" = super.buildPythonPackage rec {
    pname = "typing-extensions";
    version = "4.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0b/8e/f1a0a5a76cfef77e1eb6004cb49e5f8d72634da638420b9ea492ce8305e8/typing_extensions-4.4.0-py3-none-any.whl";
      sha256 = "17j8jbywq5cjgh6354wyh9y47cvrbyw1hqj9xhsmsrcg81j4iyhn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "urllib3" = super.buildPythonPackage rec {
    pname = "urllib3";
    version = "1.26.14";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fe/ca/466766e20b767ddb9b951202542310cba37ea5f2d792dae7589f1741af58/urllib3-1.26.14-py2.py3-none-any.whl";
      sha256 = "1qd7xh7ply92kyanm6nb5shymk9k77yckhx64iqi6nyqyz1cvvbm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
