#!/usr/bin/env bash

args=( \
  run \
  --config ./state-cluster%%INSTANCE_NUM%%/config-relay1.json \
  --database-path ./state-cluster%%INSTANCE_NUM%%/db-relay1 \
  --topology ./state-cluster%%INSTANCE_NUM%%/topology-relay1.json \
  --port %%NODE_PORT_RELAY1%% \
  --socket-path ./state-cluster%%INSTANCE_NUM%%/relay1.socket \
  "$@" \
)

echo "Starting cardano-node run with PID $$:"
echo "cardano-node ${args[*]}"
exec cardano-node "${args[@]}"
