#!/usr/bin/env bash

if ! command -v cardano-submit-api &> /dev/null; then
  echo "cardano-submit-api is not available in PATH" >&2
  exit 1
fi

testnet_magic="$(<./state-cluster%%INSTANCE_NUM%%/db-relay1/protocolMagicId)"

args=( \
  --config ./state-cluster%%INSTANCE_NUM%%/submit-api-config.json \
  --socket-path ./state-cluster%%INSTANCE_NUM%%/relay1.socket \
  --listen-address 127.0.0.1 \
  --port %%SUBMIT_API_PORT%% \
  --metrics-port %%METRICS_SUBMIT_API_PORT%% \
  --testnet-magic "$testnet_magic" \
  "$@" \
)

echo "Starting cardano-submit-api with PID $$:"
echo "cardano-submit-api ${args[*]}"
exec cardano-submit-api "${args[@]}"
