#!/bin/bash

set -euo pipefail

SOCKET_PATH="$(readlink -m "$CARDANO_NODE_SOCKET_PATH")"
STATE_CLUSTER="${SOCKET_PATH%/*}"
SCRIPT_DIR="$(readlink -m "${0%/*}")"

"$SCRIPT_DIR/deregister-pools"
supervisorctl stop all

if [ -f "$STATE_CLUSTER/supervisord.pid" ]
then
  kill "$(<"$STATE_CLUSTER/supervisord.pid")"
  echo "Cluster terminated!"
else
  echo "Cluster is not running!"
fi
