steps:
  - label: 'Run tests & generate report'
    command:
      - 'mkdir -p /scratch/cardano-node-tests'
      - './.buildkite/nightly_dbsync.sh'
    env:
      CARDANO_NODE_SOCKET_PATH_CI: '/scratch/cardano-node-tests/state-cluster0/bft1.socket'
    timeout_in_minutes: 500
    agents:
      system: x86_64-linux
    artifact_paths:
      - 'allure-report.tar.bz2'
      - 'cli_coverage.json'
      - 'testrun-report.html'
      - 'scheduling.log'
      - 'errors_all.log'

notify:
  - email: "cardano_qa_node_db_sy-aaaadudb2xnnewjhenny4cgzia@input-output-rnd.slack.com"
    if: build.state != "passed"
