steps:
  - label: 'Run tests & generate report'
    command:
      - 'mkdir -p /scratch/cardano-node-tests'
      - './.buildkite/nightly_dbsync.sh'
    env:
      CARDANO_NODE_SOCKET_PATH_CI: '/scratch/cardano-node-tests/state-cluster0/bft1.socket'
    timeout_in_minutes: 500
    agents:
      system: x86_64-linux
    artifact_paths:
      - 'allure-report.tar.xz'
      - 'cli_coverage.json'
      - 'testrun-report.html'
      - 'scheduling.log.xz'
      - 'errors_all.log'
      - 'testing_artifacts.tar.xz'
