#!/usr/bin/env bash
choice() { i=$1; shift; eval "echo \${$((i + 1))}"; }
echo "Starting cardano-node run: cardano-node run"
   echo "--config ./state-cluster/config-pool1.json"
   echo "--database-path ./state-cluster/db-pool1"
   echo "--topology ./state-cluster/topology-pool1.json"
   echo "--host-addr 127.0.0.1"
   echo "--port 30002"
   echo "--socket-path ./state-cluster/pool1.socket"
   echo "--shelley-vrf-key ./state-cluster/nodes/node-pool1/vrf.skey"
   echo "--shelley-kes-key ./state-cluster/nodes/node-pool1/kes.skey"
   echo "--shelley-operational-certificate ./state-cluster/nodes/node-pool1/op.cert"
echo "..or, once again, in a single line:"
echo "cardano-node run --config ./state-cluster/config-pool1.json --database-path ./state-cluster/db-pool1 --topology ./state-cluster/topology-pool1.json --host-addr 127.0.0.1 --port 30002 --socket-path ./state-cluster/pool1.socket --shelley-vrf-key ./state-cluster/nodes/node-pool1/vrf.skey --shelley-kes-key ./state-cluster/nodes/node-pool1/kes.skey --shelley-operational-certificate ./state-cluster/nodes/node-pool1/op.cert"


exec cardano-node run --config ./state-cluster/config-pool1.json --database-path ./state-cluster/db-pool1 --topology ./state-cluster/topology-pool1.json --host-addr 127.0.0.1 --port 30002 --socket-path ./state-cluster/pool1.socket --shelley-vrf-key ./state-cluster/nodes/node-pool1/vrf.skey --shelley-kes-key ./state-cluster/nodes/node-pool1/kes.skey --shelley-operational-certificate ./state-cluster/nodes/node-pool1/op.cert
