#!/bin/bash
choice() { i=$1; shift; eval "echo \${$((i + 1))}"; }
echo "Starting cardano-node run: cardano-node run"
   echo "--config ./state-cluster/config-bft3.json"
   echo "--database-path ./state-cluster/db-bft3"
   echo "--topology ./state-cluster/topology-bft3.json"
   echo "--host-addr 127.0.0.1"
   echo "--port 30003"
   echo "--socket-path ./state-cluster/bft3.socket"
   echo "--signing-key ./state-cluster/nodes/node-bft3/byron-deleg.key"
   echo "--delegation-certificate ./state-cluster/nodes/node-bft3/byron-deleg.json"
   echo "--shelley-vrf-key ./state-cluster/nodes/node-bft3/vrf.skey"
   echo "--shelley-kes-key ./state-cluster/nodes/node-bft3/kes.skey"
   echo "--shelley-operational-certificate ./state-cluster/nodes/node-bft3/op.cert"
echo "..or, once again, in a single line:"
echo "cardano-node run --config ./state-cluster/config-bft3.json --database-path ./state-cluster/db-bft3 --topology ./state-cluster/topology-bft3.json --host-addr 127.0.0.1 --port 30003 --socket-path ./state-cluster/bft3.socket --signing-key ./state-cluster/nodes/node-bft3/byron-deleg.key --delegation-certificate ./state-cluster/nodes/node-bft3/byron-deleg.json --shelley-vrf-key ./state-cluster/nodes/node-bft3/vrf.skey --shelley-kes-key ./state-cluster/nodes/node-bft3/kes.skey --shelley-operational-certificate ./state-cluster/nodes/node-bft3/op.cert"


exec cardano-node run --config ./state-cluster/config-bft3.json --database-path ./state-cluster/db-bft3 --topology ./state-cluster/topology-bft3.json --host-addr 127.0.0.1 --port 30003 --socket-path ./state-cluster/bft3.socket --signing-key ./state-cluster/nodes/node-bft3/byron-deleg.key --delegation-certificate ./state-cluster/nodes/node-bft3/byron-deleg.json --shelley-vrf-key ./state-cluster/nodes/node-bft3/vrf.skey --shelley-kes-key ./state-cluster/nodes/node-bft3/kes.skey --shelley-operational-certificate ./state-cluster/nodes/node-bft3/op.cert
