#!/usr/bin/env bash
choice() { i=$1; shift; eval "echo \${$((i + 1))}"; }
echo "Starting cardano-node run: cardano-node run"
   echo "--config ./state-cluster/config-bft1.json"
   echo "--database-path ./state-cluster/db-bft1"
   echo "--topology ./state-cluster/topology-bft1.json"
   echo "--host-addr 127.0.0.1"
   echo "--port 30001"
   echo "--socket-path ./state-cluster/bft1.socket"
echo "..or, once again, in a single line:"
echo "cardano-node run --config ./state-cluster/config-bft1.json --database-path ./state-cluster/db-bft1 --topology ./state-cluster/topology-bft1.json --host-addr 127.0.0.1 --port 30001 --socket-path ./state-cluster/bft1.socket"


exec cardano-node run --config ./state-cluster/config-bft1.json --database-path ./state-cluster/db-bft1 --topology ./state-cluster/topology-bft1.json --host-addr 127.0.0.1 --port 30001 --socket-path ./state-cluster/bft1.socket
