#!/bin/bash
choice() { i=$1; shift; eval "echo \${$((i + 1))}"; }
echo "Starting cardano-node run: cardano-node run"
   echo "--config ./state-cluster/config-bft2.json"
   echo "--database-path ./state-cluster/db-bft2"
   echo "--topology ./state-cluster/topology-bft2.json"
   echo "--host-addr 127.0.0.1"
   echo "--port 30002"
   echo "--socket-path ./state-cluster/bft2.socket"
   echo "--signing-key ./state-cluster/nodes/node-bft2/byron-deleg.key"
   echo "--delegation-certificate ./state-cluster/nodes/node-bft2/byron-deleg.json"
   echo "--shelley-vrf-key ./state-cluster/nodes/node-bft2/vrf.skey"
   echo "--shelley-kes-key ./state-cluster/nodes/node-bft2/kes.skey"
   echo "--shelley-operational-certificate ./state-cluster/nodes/node-bft2/op.cert"
echo "..or, once again, in a single line:"
echo "cardano-node run --config ./state-cluster/config-bft2.json --database-path ./state-cluster/db-bft2 --topology ./state-cluster/topology-bft2.json --host-addr 127.0.0.1 --port 30002 --socket-path ./state-cluster/bft2.socket --signing-key ./state-cluster/nodes/node-bft2/byron-deleg.key --delegation-certificate ./state-cluster/nodes/node-bft2/byron-deleg.json --shelley-vrf-key ./state-cluster/nodes/node-bft2/vrf.skey --shelley-kes-key ./state-cluster/nodes/node-bft2/kes.skey --shelley-operational-certificate ./state-cluster/nodes/node-bft2/op.cert"


exec cardano-node run --config ./state-cluster/config-bft2.json --database-path ./state-cluster/db-bft2 --topology ./state-cluster/topology-bft2.json --host-addr 127.0.0.1 --port 30002 --socket-path ./state-cluster/bft2.socket --signing-key ./state-cluster/nodes/node-bft2/byron-deleg.key --delegation-certificate ./state-cluster/nodes/node-bft2/byron-deleg.json --shelley-vrf-key ./state-cluster/nodes/node-bft2/vrf.skey --shelley-kes-key ./state-cluster/nodes/node-bft2/kes.skey --shelley-operational-certificate ./state-cluster/nodes/node-bft2/op.cert
