#!/usr/bin/env bash

echo "Starting cardano-node run with PID $$: cardano-node run"
   echo "--config ./state-cluster%%INSTANCE_NUM%%/config-bft1.json"
   echo "--database-path ./state-cluster%%INSTANCE_NUM%%/db-bft1"
   echo "--topology ./state-cluster%%INSTANCE_NUM%%/topology-bft1.json"
   echo "--host-addr 127.0.0.1"
   echo "--port %%NODE_PORT_BASE%%"
   echo "--socket-path ./state-cluster%%INSTANCE_NUM%%/bft1.socket $*"

echo "..or, once again, in a single line:"
echo "cardano-node run --config ./state-cluster%%INSTANCE_NUM%%/config-bft1.json --database-path ./state-cluster%%INSTANCE_NUM%%/db-bft1 --topology ./state-cluster%%INSTANCE_NUM%%/topology-bft1.json --host-addr 127.0.0.1 --port %%NODE_PORT_BASE%% --socket-path ./state-cluster%%INSTANCE_NUM%%/bft1.socket $*"


exec cardano-node run --config ./state-cluster%%INSTANCE_NUM%%/config-bft1.json --database-path ./state-cluster%%INSTANCE_NUM%%/db-bft1 --topology ./state-cluster%%INSTANCE_NUM%%/topology-bft1.json --host-addr 127.0.0.1 --port %%NODE_PORT_BASE%% --socket-path ./state-cluster%%INSTANCE_NUM%%/bft1.socket "$@"
