name: db-sync - snapshot restoration test

on:
  workflow_dispatch:
    branches:
      - db_sync_tests
    inputs:
      node_pr:
        description: node pull request number
        required: true
        default: "3458"
      node_branch:
        description: node branch or tag
        required: true
        default: "1.33.0"
      node_version:
        description: node version - 1.33.0-rc2 (tag number) or 1.33.0 (release number - for released versions) or 1.33.0_PR2124 (for not released and not tagged runs with a specific node PR/version)
        required: true
        default: "1.33.0"
      db_sync_branch:
        description: db-sync branch or tag
        required: true
        default: "release/12.0.x"
      db_sync_version:
        description: db-sync version - 12.0.0-rc2 (tag number) or 12.0.2 (release number - for released versions) or 12.0.2_PR2124 (for not released and not tagged runs with a specific db_sync PR/version)
        required: true
        default: "12.0.2"
      environment:
        description: Environment on which to run the tests - shelley_qa, testnet, staging or mainnet
        required: true
        default: "testnet"
      snapshot_url:
        description: Snapshot URL
        required: true
        default: "https://updates-cardano-testnet.s3.amazonaws.com/cardano-db-sync/12/db-sync-snapshot-schema-12-block-3411499-x86_64.tgz"

jobs:
  db_sync_test:
    runs-on: ubuntu-latest
    steps:
      - name: trigger the Buildkite pipeline - run db sync snapshot restoration
        env:
          BUILDKITE_API_ACCESS_TOKEN: ${{ secrets.BUILDKITE_API_ACCESS_TOKEN }}
          AWS_DB_USERNAME: ${{ secrets.AWS_DB_USERNAME }}
          AWS_DB_PASS: ${{ secrets.AWS_DB_PASS }}
          AWS_DB_NAME: ${{ secrets.AWS_DB_NAME }}
          AWS_DB_HOSTNAME: ${{ secrets.AWS_DB_HOSTNAME }}
        uses: zegocover/buildkite-pipeline-action@master
        with:
          branch: db_sync_tests
          access_token: '${{ secrets.BUILDKITE_API_ACCESS_TOKEN }}'
          pipeline: 'input-output-hk/qa-db-sync-snapshot-restoration'
          message: ':github: Triggered by GitHub Action'
          env: '{
          "node_pr":"${{ github.event.inputs.node_pr }}",
          "node_branch":"${{ github.event.inputs.node_branch }}",
          "node_version":"${{ github.event.inputs.node_version }}",
          "db_sync_branch":"${{ github.event.inputs.db_sync_branch }}",
          "db_sync_version":"${{ github.event.inputs.db_sync_version }}",
          "environment":"${{ github.event.inputs.environment }}",
          "snapshot_url":"${{ github.event.inputs.snapshot_url }}",
          "AWS_DB_USERNAME":"${{ secrets.AWS_DB_USERNAME }}",
          "AWS_DB_PASS":"${{ secrets.AWS_DB_PASS }}",
          "AWS_DB_NAME":"${{ secrets.AWS_DB_NAME }}",
          "AWS_DB_HOSTNAME":"${{ secrets.AWS_DB_HOSTNAME }}"
          }'
