name: Nightly tests PV11

on:
  schedule:
    - cron: '15 02 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  nightly_job:
    if: github.repository_owner == 'IntersectMBO' || github.event_name != 'schedule'
    # reusable workflow from local repo and same branch as this config
    uses: ./.github/workflows/regression_reusable.yaml
    with:
      env-path: runner/env_nightly_pv11
    secrets:
      CI_FAIL_MAILS: ${{ secrets.NIGHTLY_FAIL_MAILS }}
      GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
      GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
      CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
