name: Nightly tests Conway no CC

on:
  schedule:
    - cron: '15 04 * * *'
  workflow_dispatch:

jobs:
  nightly_job:
    if: github.repository_owner == 'IntersectMBO' || github.event_name != 'schedule'
    # reusable workflow from local repo and same branch as this config
    uses: ./.github/workflows/regression_reusable.yaml
    with:
      env-path: .github/env_nightly_conway_nocc
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CI_FAIL_MAILS: ${{ secrets.NIGHTLY_FAIL_MAILS }}
      GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
      GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
