name: CLI regression tests

on:
  workflow_dispatch:
    inputs:
      node_rev:
        description: "cardano-node revision (default: HEAD)"
        required: false
      node_branch:
        description: "cardano-node branch (default: master)"
        required: false
      cluster_era:
        description: "Cluster era (default: empty)"
        required: false
      tx_era:
        description: "Tx era (default: empty)"
        required: false
      test_threads:
        description: "Num of pytest workers (default: 15)"
        required: false
      clusters_count:
        description: "Num of cluster instances (default: 9)"
        required: false

jobs:
  cli_regression:
    runs-on: ubuntu-latest
    steps:
      - name: trigger the Buildkite pipeline - run CLI regression tests
        uses: zegocover/buildkite-pipeline-action@master
        with:
          access_token: "${{ secrets.BUILDKITE_API_ACCESS_TOKEN }}"
          pipeline: "input-output-hk/cardano-node-tests-nightly"
          message: ":github: Triggered by GitHub Action"
          env: '{
          "NODE_REV":"${{ github.event.inputs.node_rev }}",
          "NODE_BRANCH":"${{ github.event.inputs.node_branch }}",
          "CLUSTER_ERA":"${{ github.event.inputs.cluster_era }}",
          "TX_ERA":"${{ github.event.inputs.tx_era }}",
          "TEST_THREADS":"${{ github.event.inputs.test_threads }}",
          "CLUSTERS_COUNT":"${{ github.event.inputs.clusters_count }}"
          }'
