name: CLI regression tests

on:
  workflow_dispatch:
    inputs:
      tests_rev:
        description: "cardano-node-tests revision (default: HEAD)"
        required: false
      node_rev:
        description: "cardano-node revision (default: HEAD)"
        required: false
      node_branch:
        description: "cardano-node branch (default: master)"
        required: false
      cluster_era:
        description: "Cluster era (default: empty)"
        required: false
      tx_era:
        description: "Tx era (default: empty)"
        required: false

jobs:
  cli_regression:
    runs-on: ubuntu-latest
    steps:
      - name: trigger the Buildkite pipeline - run CLI regression tests
        uses: zegocover/buildkite-pipeline-action@master
        with:
          access_token: "${{ secrets.BUILDKITE_API_ACCESS_TOKEN }}"
          pipeline: "input-output-hk/cardano-node-tests"
          commit: "${{ github.event.inputs.tests_rev }}"
          message: ":github: Triggered by GitHub Action"
          env: '{
          "NODE_REV":"${{ github.event.inputs.node_rev }}",
          "NODE_BRANCH":"${{ github.event.inputs.node_branch }}",
          "CLUSTER_ERA":"${{ github.event.inputs.cluster_era }}",
          "TX_ERA":"${{ github.event.inputs.tx_era }}"
          }'
