name: 01 Regression tests

on:
  workflow_dispatch:
    inputs:
      node_rev:
        description: "cardano-node revision"
        default: master
      cluster_era:
        type: choice
        description: "Cluster era"
        options:
        - conway 9
        - conway 10
        default: conway 9
      tx_era:
        type: choice
        description: "Tx era"
        options:
        - default
        - conway
        - babbage
        default: default
      markexpr:
        type: choice
        description: "Selection of tests"
        options:
        - all
        - smoke
        - plutus
        - plutus and smoke
        - not long
        - conway only
        default: all
      topology:
        type: choice
        description: "Network topology"
        options:
        - legacy
        - p2p
        - mixed
        default: legacy
      byron_cluster:
        type: boolean
        default: false
        description: "Start cluster in Byron era"
      testrun_name:
        required: false
        description: "Test run name (internal)"
      skip_passed:
        type: boolean
        default: false
        description: "Skip tests that already passed (internal)"

run-name: ${{ inputs.testrun_name && 'Run:' || ''}} ${{ inputs.testrun_name }} ${{ (inputs.testrun_name && inputs.skip_passed) && ':repeat:' || '' }}

jobs:
  regression_tests:
    # reusable workflow from local repo and same branch as this config
    uses: ./.github/workflows/regression_reusable.yaml
    with:
      node_rev: ${{ inputs.node_rev }}
      cluster_era: ${{ inputs.cluster_era }}
      tx_era: ${{ inputs.tx_era }}
      markexpr: ${{ inputs.markexpr }}
      topology: ${{ inputs.topology }}
      byron_cluster: ${{ inputs.byron_cluster }}
      testrun_name: ${{ inputs.testrun_name }}
      skip_passed: ${{ inputs.skip_passed }}
      env-path: .github/env_regression
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TCACHE_BASIC_AUTH: ${{ secrets.TCACHE_BASIC_AUTH }}
      TCACHE_URL: ${{ secrets.TCACHE_URL }}
