name: repo_tests

on:
  pull_request:
    branches:
    - master

env:
  PY_COLORS: "1"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Set up python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('poetry.lock') }}
    - name: Install project
      run: SETUPTOOLS_ENABLE_FEATURES="legacy-editable" poetry install --no-interaction --with dev
    - name: Load cached pre-commit env
      id: cached-pre-commit
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Install pre-commit hooks
      run: |
        mkdir -p ~/.cache/pre-commit
        true > ~/.cache/pre-commit/pre-commit.log
        poetry run pre-commit install-hooks --color=always
        retval="$?"
        if [ "$retval" -ne 0 ]; then
          cat ~/.cache/pre-commit/pre-commit.log
        fi
        exit "$retval"
    - name: Run pre-commit linters
      run: poetry run pre-commit run -a --show-diff-on-failure --color=always
    - name: Run framework tests
      run: poetry run pytest --doctest-modules framework_tests cardano_node_tests/utils/
