name: sync tests

on: [push]

jobs:
  sync_mainnet:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: checkout github repo
        uses: actions/checkout@v2
        with:
          ref: 'dorin/sync_tests'
      - name: sync test
        run: ./sync_tests/sync_test_mainnet.sh
        shell: bash