name: shell commands

on: [push]

jobs:
  sync_testnet:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github repo
        uses: actions/checkout@v1
        ref: 'dorin/sync_tests'
      - name: sync test on testnet
        run: ./.github/sync_tests/sync_times_ci_testnet.sh
